language: node_js
node_js:
- stable
install:
- npm install
deploy:
  provider: lambda
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  function_name: shuffleTrip
  region: eu-west-2
  handler_name: handler
  runtime: nodejs6.10
  publish: true
  zip: deploy.zip
  role: "$ROLE"
  on:
    all_branches: true
before_deploy:
- zip -r deploy.zip index.js package.json node_modules/
after_deploy:
- unzip -l deploy.zip
