language: node_js
node_js:
- stable
install:
- npm install
deploy:
  provider: lambda
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  function_name: shuffleTrip
  region: eu-west-2
  handler_name: handler
  runtime: nodejs6.10
  publish: true
  zip: deploy.zip
  role: "$ROLE"
  on:
    all_branches: true
before_deploy:
- zip -r deploy.zip index.js package.json node_modules/ airports.json
after_deploy:
- unzip -l deploy.zip
env:
  global:
  - secure: Fz/eisL1/Gu1B7URRZDrcaKOVH2hbuFvWGhTAQ2E06IPjWu/GBete0HQzzlV/WlIWLOIbcMzsb2WYm8Yj/+sUFJOlUWkcTwfMP8YRB6RgJLb5awlzylurGgllQ/4Kn0/6CVBocmWKfZ5UGmLTXIy1TISjWgn8Qvqn/Quo7FBPKjJznOVXYagcClx3c6L0PJQ/n7lNkJy0c/cnxHjpIw3pdfANELyjPWhuP3st+efS9BzTurTa9tX8bGMqo4u4xk2YmMLnBNXg56mUFpQshPQWG4OJQ+Gqnh9QzNoYh7k8blD6zLoB2yVO6mjbnwQbLL6iZOIvNy+P6fGTNr+rwCjH2CdueArZkzbmKkMeomeEq8PRrYrxxzvGKzLsqmbwKtcciJM8RW5LUMx3B0K7Jq776Pwr7rEtpULUEKNpR4VR+I1FJ7hBjqoOSYxIGcJJzAxMJbCJelNA1r7kDrnfYYFWPrzfZaTNmNPqteKIXWVZXyT1kzEijx6JLtI/Xg0UhCnkB+Ol09Akq3172oEtPOkttPPEVsMb5d61lvFAOEPYIZUEtgL7b4EJIbwYgS4Gm6uZNc3n8x2ooRvk/AWmTyJoEwAxr2wk9+CtI+ICxywvWDq+skNOZ/U0Wm3jgWPPDKicIxOdrx8HlAvtphnRgdva7uIM3K/ZdQoV2CGOqYKWqE=
  - secure: RYtFoUpPTNKWUEJuYd/6W9yEEd1TVdUO90qZFYeA5B/+uXZm01U/l3mlEbILPdakkgocfRBdnk8NJDnhB7NCmHQgEmOgHjqc/c+JLeiQl7apeB9oBTSA9M9bcL6PgK2IMla0BiWlaoL1EyEiXAddOT3eJy06/W7ieZlG1EnnsD4I+L/nYjIAmwrbpGZ85kUzdsebpndT0frtFknS/U2Vxsmd+sAMR4gditPOba0syuMNErc9bBJm1dGFqSoP7qPmztDdUMYDSPE530pP0ZfS6FcP+rpUgwpVxcCLj8+V1p6FrsOJLRLfytvNh14mi8KORT+f3YSbYgSshT3SHWTrxP8AVbTeSmgCju1twJCiVBIxsPnSJEZF9qteUDEr1aWPROOWnMa9bRSnYZ2OnYLZGJTPxCbdRqOqN2GCgrmJl/8lGOuiIgng40XYICli3CpCBceNEEsciH6rzwDNKtODu6atKy/704N/tceois/+IIgylvWfjyEOQb2Yb6gTjMTJO4MJecuG+LeBLCg6k2FxEw/pfn2UGpYo2J+XINA9ZSV/yD5Il5F2VxXJ++e6tWcOG7RJhyi6cHphqapvyUH4scJXU5mIdrmROaShz7i4hVvhGl5E/Fh409x+KrdB8ysh+Apjpp16bQxrGkLJXK4+Q+UFZvro69kbo0io0RjcSBA=
  - secure: Uz5IfKq/1VFquFXh9wt7U9zfoMlbnrsPqRk7M5Uo5hMy+4ImC60JXW++n0GS+R2kjm1zXFCQBMErEKS4na63a9D/ydVdgL276NTmWZZ/1L5RcqlzFz+dzK3b0lkSLqKVaB9W3rAPiIx13JUHaP+6m63sn5Hqkc+hLEse3WQwFFjz2HhpWQlsLzZkIT9kq5Vh9pVKmqFadKlrSIt17JkqsD6wPHXWH96LKRNoUllV3PPwfbNN+7jNbSW5j9oGeHDk9CwGAZzO7maWbBS+ni5pCnDujzDlMvqLpSghA/Brm1HoVIkq0GUX3JrTQyf1HOkhPchBrCy/OGhmvNPfF9PtyXjJk+mtqvBblfifF6YgWJ5nTNgXQJ7u3NQBem2CCZYwaYjX9SDYupdi8PvdXnEHhWaHHYWXi7CrTQbCImCuAW9qteJ/iFXB2LpNXp73zydptM2aqfjiJvMtn7yEJ3ag6yYL0khmagPfDj57uIm4qC67ymZ8QLGzycWzFSCm5vEfdo7F7LLuyk5dxyUMGYSDoNSYWdaRgJDX8w06OAcBQD/PePj9ZpwSvBGlbArB1hG1QBP4aYi2r6v/AISXDoX35aZG/gHauEu31hsefOPLaNahnCze9NUj7yI7Ll0Aja4h/+rmLhvULQOhbePaKdhoM/0OTznjbWNZ7t1JiZtfrso=
